### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wiseaidev** [opensass/aibook#19]
- [ ] Wire up Stripe
- [ ] mv jwt_storage middlware
- [ ] More DRY
- [ ] Fix Deployment
- [ ] Decouple Prompts Static data from functions
